import { Express } from 'express';
import healthRoutes from '../modules/infrastructure/routes/health.routes.js';
import authRoutes from '../modules/auth/routes/auth.routes.js';
import bookingsRoutes from '../modules/bookings/routes/bookings.routes.js';
import paymentsRoutes from '../modules/payments/routes/payments.routes.js';
import guaranteesRoutes from '../modules/guarantees/routes/guarantees.routes.js';
import smartScheduleRoutes from '../modules/providers/routes/smart-schedule.routes.js';
import onboardingChatRoutes from '../modules/chat/routes/onboarding-chat.routes.js';
import userAssistantRoutes from '../modules/chat/routes/user-assistant.routes.js';
import messageRoutes from '../modules/chat/routes/messages.routes.js';
import ttsRoutes from '../modules/speech/routes/tts.routes.js';
import supplyOptimizationRoutes from '../modules/analytics/routes/supply-optimization.routes.js';
import analyticsEventsRoutes from '../modules/analytics/routes/analytics-events.routes.js';
import adminRoutes from '../modules/admin/routes/admin.routes.js';
import notificationsRoutes from '../modules/notifications/routes/notifications.routes.js';
import searchRoutes from '../modules/search/routes/search.routes.js';
import storageRoutes from '../modules/infrastructure/routes/storage.routes.js';
import geocodeRoutes from '../modules/infrastructure/routes/geocode.routes.js';
import usersRoutes from '../modules/users/routes/users.routes.js';
import listingsRoutes from '../modules/listings/routes/listings.routes.js';
import reviewsRoutes from '../modules/reviews/routes/reviews.routes.js';
import providersRoutes from '../modules/providers/routes/providers.routes.js';
import verificationRoutes from '../modules/verification/routes/verification.routes.js';
import safetyRoutes from '../modules/fraud/routes/safety.routes.js';
import fraudRoutes from '../modules/fraud/routes/fraud.routes.js';
import couponsRoutes from '../modules/coupons/routes/coupons.routes.js';
import wishlistsRoutes from '../modules/wishlists/routes/wishlists.routes.js';
import translationRoutes from '../modules/translation/routes/translation.routes.js';

export function registerRoutes(app: Express) {
  app.use('/', healthRoutes);
  app.use('/api/auth', authRoutes);
  app.use('/api/bookings', bookingsRoutes);
  app.use('/api/payments', paymentsRoutes);
  app.use('/api/guarantees', guaranteesRoutes);
  app.use('/api/smart-schedule', smartScheduleRoutes);
  app.use('/api/providers', providersRoutes);
  app.use('/api/onboarding-chat', onboardingChatRoutes);
  app.use('/api/assistant', userAssistantRoutes);
  app.use('/api/tts', ttsRoutes);
  app.use('/api/chat', messageRoutes);
  app.use('/api/supply-optimization', supplyOptimizationRoutes);
  app.use('/api/analytics', analyticsEventsRoutes);
  app.use('/api/admin', adminRoutes);
  app.use('/api/notifications', notificationsRoutes);
  app.use('/api/search', searchRoutes);
  app.use('/api/users', usersRoutes);
  app.use('/api/listings', listingsRoutes);
  app.use('/api/reviews', reviewsRoutes);
  app.use('/api/verification', verificationRoutes);
  app.use('/api/safety', safetyRoutes);
  app.use('/api/fraud', fraudRoutes);
  app.use('/api/storage', storageRoutes);
  app.use('/api/geocode', geocodeRoutes);
  app.use('/api/coupons', couponsRoutes);
  app.use('/api/wishlist', wishlistsRoutes);
  app.use('/api/translation', translationRoutes);
}
