-- Phase 4 of the assistant agent overhaul.
--
-- Per-user memory the agent can read at the start of every turn and write
-- to via the `remember_preference` tool. The intent is "compact long-term
-- profile" not "full conversation log" — that's why the cap is small and
-- the row is keyed by user_id (one row per user, not per session).
--
-- Shape lives in the application layer (`AssistantMemory` interface in
-- user-assistant-memory.service.ts):
--   {
--     preferences: { budget?, locations?, dietaryNeeds?, ... },
--     history:    { recentSearches: [...], lastBookingId? },
--     flags:      { hostileSentimentEvents, consecutiveFailures }
--   }
--
-- Why a hard 4KB cap (not "soft, monitor it"):
--   1. Bounded prompt cost — the entire memory blob gets injected into
--      the system prompt every turn. Letting it grow unbounded means
--      one user with a chatty week silently 10x's our LLM bill.
--   2. Prevents schema drift — if the JSON keeps growing, every agent
--      prompt edit becomes a backfill exercise. 4KB forces eviction.
--   3. The history.recentSearches[] is the only field that grows
--      naturally; the service layer caps it at 20 entries and evicts
--      oldest when the row would exceed 4096 bytes.
--
-- Concurrency: optimistic locking via updated_at. Concurrent writes from
-- a voice + text turn racing on the same user are rare but possible;
-- the service compares-and-swaps and re-reads on conflict.

-- user_id is the Firebase/Cognito UID (UUID-shaped). Auth users live
-- outside Postgres in this stack — same pattern as user_profiles /
-- provider_profiles in the portable schema — so no FK constraint.
-- Orphaned-row cleanup is the app's responsibility (Phase 6 cron).
CREATE TABLE IF NOT EXISTS public.user_assistant_memory (
  user_id    UUID PRIMARY KEY,
  memory     JSONB NOT NULL DEFAULT '{}'::jsonb,
  -- Generated bytes column lets the CHECK enforce the cap without the
  -- service layer having to remember to compute octet_length on every
  -- write. STORED so the planner sees it for any future filtering.
  bytes      INT GENERATED ALWAYS AS (octet_length(memory::text)) STORED,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT user_assistant_memory_size_check CHECK (octet_length(memory::text) <= 4096)
);

-- We always read by user_id (the PK already covers that), so no extra
-- indexes today. Add (updated_at) only if a "stale memory cleanup" job
-- materialises later.

COMMENT ON TABLE public.user_assistant_memory IS
  'Phase 4 assistant agent memory. One row per user; capped at 4KB JSON. See user-assistant-memory.service.ts for shape + eviction policy.';
